@startuml

abstract class AbstractAbstraction
{
    response(AbstractImplementor $implementor)
}

class Abstraction extends AbstractAbstraction
{
    response(AbstractImplementor $implementor)
}

abstract class AbstractImplementor
{
    format()
}

class Implementor extends AbstractImplementor
{
    format()

}

Abstraction o-- Implementor

@enduml