@startuml
class Singleton {
private static $instance
    public static function getInstance()
    private function __construct()
    private function __clone()
    private function __wakeup()
}

@enduml